version: '3'

services:
  auto_symlink:
    image: shenxianmq/auto_symlink:latest
    container_name: auto_symlink
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 8095:8095
    volumes:
      - /volume1/CloudNAS:/volume1/CloudNAS:rslave
      - /volume2/Media:/volume2/Media
      - /volume1/docker/auto_symlink/config:/app/config
      - /volume1/docker/auto_symlink/backup:/app/backup
    restart: unless-stopped
    logging:
      options:
        max-size: '10m'
        max-file: '3'
